### ISSUE TITLE
Reproducing Figure 1

### ISSUE THREAD

**Issue by thanhnguyentang** [sparisi/td-reg#2]
Hi @sparisi, 

Really nice work! I am particularly interested in Figure 1 where you showed a simple analytic example. I was wondering which specific task (with states of 2 dimensions) that you used for this experiment? In addition, are you planning to produce the code for this part as well? If so, it would be very helpful :-). 

Thank you in advance. 

Best Regards,
-Thanh

**Comment by sparisi** [comment]
Hi Thanh,

Thanks!

For Figure 1 I randomly drew the policy parameters, saved and fixed them for all the runs, then drew randomly the ones for the critic at every run. The seeds for the critic parameters used in the Figure are 1, 4, 6, but I didn't save the ones of the policy, so I can't replicate **exactly** Figure 1. 

You can get a similar figure by doing to following, though:
- At the beginning of `run_dpg.m` and `run_tdreg.m`, after calling `common_settings`, fix `theta` (I just tested it with `theta = [-0.2218, -0.1124; -0.1124, -0.0588];`).
- Run the trials with seeds 1, 4, 6, (`run_dpg(1)`, `run_tdreg(1)`, ...).
- Run `plot_quiver_many.m`, changing line 42 to `folder = './';`.

If you use the `theta` I wrote above, you should see that all 3 runs of DPG completely diverge, while TDREG goes to the optimum (not reaching it, because that `theta` corresponds to a very bad policy, very far from the optimum).

Hope this helps!

**Comment by thanhnguyentang** [comment]
Hi @sparisi, 

Thanks for your quick response and for your detailed explanation. 

I am not sure if I really understand this: 

> For Figure 1 I randomly drew the policy parameters, saved and fixed them for all the runs   

For that experiment, did you have a specific mdp (e.g., gridworld) to interact with (so that you can compute the value function of any 2-dimensional parameterized policy and plot the expected value function in Figure 1)? If so, my question was what is that mdp task that you used in the Figure 1? :-) 

Thank you. 

Best, 
-Thanh

**Edit**:  I believe the mdp environment you used for Figure 1 is also LQR (which by the way has closed-form Q-function, expected return, and TD error)? Thanks!

**Comment by sparisi** [comment]
Hi Thanh,

> I am not sure if I really understand this:
> 
> > For Figure 1 I randomly drew the policy parameters, saved and fixed them for all the runs

At the beginning of each run, the policy and the critic parameter `theta` and `omega`, respectively, initialized randomly (see `common_settings.m`). For Figure 1 we fixed `theta` and kept `omega` random (always with seeds from 1 to 50, i.e., `rng(1)`, `rng(2)`, ...). Then we plotted only seeds 1, 4, 6.
 
> **Edit**: I believe the mdp environment you used for Figure 1 is also LQR (which by the way has closed-form Q-function, expected return, and TD error)? Thanks!

Correct!

Best,
Simone

**Comment by thanhnguyentang** [comment]
Hi Simone, 

Thanks for your response. 
1. 
> Edit: I believe the mdp environment you used for Figure 1 is also LQR (which by the way has closed-form Q-function, expected return, and TD error)? Thanks!
> > Correct! 

This is absolutely interesting! Thank you. 

Regarding this one for Figure 1, did you use 2D LQR? Also, did you use a parameterized policy in the form of: `\pi(s; \theta) = \theta s` in the experiment for Figure 1? If this is the case (and if it is 2D LQR), it seems that `\theta` is  4-dimensional (in the form of 2x2, because `s` is 2-dimensional) but in your Figure 1, the theta space has 2 dimensions? Did I miss something on that?  

2. 

> At the beginning of each run, the policy and the critic parameter theta and omega, respectively, initialized randomly (see common_settings.m). For Figure 1 we fixed theta and kept omega random (always with seeds from 1 to 50, i.e., rng(1), rng(2), ...). Then we plotted only seeds 1, 4, 6.

Oh I see. This is about the initial values for `\theta` and `\omega`.  

Thank you. 

Best,
-Thanh

**Comment by sparisi** [comment]
Hi Thanh,

> Regarding this one for Figure 1, did you use 2D LQR? Also, did you use a parameterized policy in the form of: `\pi(s; \theta) = \theta s` in the experiment for Figure 1? If this is the case (and if it is 2D LQR), it seems that `\theta` is 4-dimensional (in the form of 2x2, because `s` is 2-dimensional) but in your Figure 1, the theta space has 2 dimensions? Did I miss something on that?

Yes, it is the 2D LQR. I plotted only the diagonal elements of `theta`, because the optimal matrix is also diagonal, so the others elements will go to 0. (I wrote about it in Appendix A).

Best,
Simone

**Comment by thanhnguyentang** [comment]
Hi Simone, 

> Yes, it is the 2D LQR. I plotted only the diagonal elements of theta, because the optimal matrix is also diagonal, so the others elements will go to 0. (I wrote about it in Appendix A).

I see. Thank you. 

Best,
-Thanh
